[[pages]]
path = "intro.py"
name = "Introduction"
icon = "ğŸ "

[[pages]]
path = "pages/1ì°¨ì‹œ.py"
name = "1ì°¨ì‹œ"
icon = ":books:"

[[pages]]
name = "2ì°¨ì‹œ"
icon = "ğŸ’ª"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
path = "pages/2ì°¨ì‹œ.py"
name = "2ì°¨ì‹œ í™œë™ 1"
icon = ":books:"

# Unless you explicitly say in_section = false`
[[pages]]
path = "pages/3ì°¨ì‹œ.py"
name = "3ì°¨ì‹œ"
in_section = false